"""Updated driver and customer models

Revision ID: 6d4f294e105d
Revises: ef051da8da83
Create Date: 2025-03-24 05:29:41.394358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4f294e105d'
down_revision = 'ef051da8da83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('vehicle_info', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('license_image', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_column('license_image')
        batch_op.drop_column('vehicle_info')
        batch_op.drop_column('phone')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('student_id')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
