"""Updated books model

Revision ID: 861088e351d8
Revises: 5987c292d4d7
Create Date: 2025-03-24 03:44:51.638447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861088e351d8'
down_revision = '5987c292d4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('faculty')

    # ### end Alembic commands ###
